GET http://localhost:3000/api/users



### 
GET http://localhost:3000/api/users/4



### 



POST http://localhost:3000/auth
Content-Type: application/json 

{
    "firstName": "Admin",
    "lastName": "Groupomania",
    "email": "admin@admin.fr",
    "password": "adminPassword88"
}



###

DELETE http://localhost:3000/api/users/3

