GET http://localhost:3000/api/users



### 
GET http://localhost:3000/api/users/4



### 



POST http://localhost:3000/auth
Content-Type: application/json 

{
    "firstName": "Theo",
    "lastName": "Trouillet",
    "email": "justtesting@outlook.fr",
    "password": "blablablabla"
}



###

DELETE http://localhost:3000/api/users/3

